# Generated by Django 4.0.4 on 2022-08-15 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_number', models.CharField(editable=False, max_length=12, unique=True)),
                ('incident_details', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'low'), ('medium', 'medium'), ('high', 'high')], default='high', max_length=6)),
                ('incident_status', models.CharField(choices=[('open', 'open'), ('in progress', 'in progress'), ('closed', 'closed')], default='open', max_length=11)),
                ('reported_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('reporter_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
