# Generated by Django 4.0.4 on 2022-08-16 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assesment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='reportername',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
