# Generated by Django 4.0.4 on 2022-08-16 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assesment', '0002_incident_reportername'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incident',
            old_name='reportername',
            new_name='name',
        ),
    ]
